/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubscribersOnlyRouteImport } from './routes/subscribers-only'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PantryRouteImport } from './routes/pantry'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecipesIndexRouteImport } from './routes/recipes/index'
import { Route as PollsIndexRouteImport } from './routes/polls/index'
import { Route as NotificationsIndexRouteImport } from './routes/notifications/index'
import { Route as MessagesIndexRouteImport } from './routes/messages/index'
import { Route as GroceryIndexRouteImport } from './routes/grocery/index'
import { Route as CollectionsIndexRouteImport } from './routes/collections/index'
import { Route as CalendarsIndexRouteImport } from './routes/calendars/index'
import { Route as SharedTokenRouteImport } from './routes/shared/$token'
import { Route as RecipesTagsRouteImport } from './routes/recipes/tags'
import { Route as RecipesNewRouteImport } from './routes/recipes/new'
import { Route as PollsPollIdRouteImport } from './routes/polls/$pollId'
import { Route as MessagesConversationIdRouteImport } from './routes/messages/$conversationId'
import { Route as GroceryListIdRouteImport } from './routes/grocery/$listId'
import { Route as DevLoginRouteImport } from './routes/dev/login'
import { Route as CollectionsSavedRouteImport } from './routes/collections/saved'
import { Route as CollectionsBrowseRouteImport } from './routes/collections/browse'
import { Route as CalendarsCalendarIdRouteImport } from './routes/calendars/$calendarId'
import { Route as ApiUploadPdfRouteImport } from './routes/api/upload-pdf'
import { Route as ApiUploadRouteImport } from './routes/api/upload'
import { Route as ApiRotateImageRouteImport } from './routes/api/rotate-image'
import { Route as UUsernameIndexRouteImport } from './routes/u/$username/index'
import { Route as RecipesRecipeIdIndexRouteImport } from './routes/recipes/$recipeId/index'
import { Route as CollectionsCollectionIdIndexRouteImport } from './routes/collections/$collectionId/index'
import { Route as AuthGoogleIndexRouteImport } from './routes/auth/google/index'
import { Route as UUsernameFollowingRouteImport } from './routes/u/$username/following'
import { Route as UUsernameFollowersRouteImport } from './routes/u/$username/followers'
import { Route as RecipesRecipeIdPdfRouteImport } from './routes/recipes/$recipeId/pdf'
import { Route as RecipesRecipeIdEditRouteImport } from './routes/recipes/$recipeId/edit'
import { Route as RecipesRecipeIdCookRouteImport } from './routes/recipes/$recipeId/cook'
import { Route as CollectionsCollectionIdPdfRouteImport } from './routes/collections/$collectionId/pdf'
import { Route as AuthGoogleCallbackRouteImport } from './routes/auth/google/callback'
import { Route as ApiWebhooksStripeRouteImport } from './routes/api/webhooks/stripe'

const SubscribersOnlyRoute = SubscribersOnlyRouteImport.update({
  id: '/subscribers-only',
  path: '/subscribers-only',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PantryRoute = PantryRouteImport.update({
  id: '/pantry',
  path: '/pantry',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesIndexRoute = RecipesIndexRouteImport.update({
  id: '/recipes/',
  path: '/recipes/',
  getParentRoute: () => rootRouteImport,
} as any)
const PollsIndexRoute = PollsIndexRouteImport.update({
  id: '/polls/',
  path: '/polls/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsIndexRoute = NotificationsIndexRouteImport.update({
  id: '/notifications/',
  path: '/notifications/',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesIndexRoute = MessagesIndexRouteImport.update({
  id: '/messages/',
  path: '/messages/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroceryIndexRoute = GroceryIndexRouteImport.update({
  id: '/grocery/',
  path: '/grocery/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsIndexRoute = CollectionsIndexRouteImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarsIndexRoute = CalendarsIndexRouteImport.update({
  id: '/calendars/',
  path: '/calendars/',
  getParentRoute: () => rootRouteImport,
} as any)
const SharedTokenRoute = SharedTokenRouteImport.update({
  id: '/shared/$token',
  path: '/shared/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesTagsRoute = RecipesTagsRouteImport.update({
  id: '/recipes/tags',
  path: '/recipes/tags',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesNewRoute = RecipesNewRouteImport.update({
  id: '/recipes/new',
  path: '/recipes/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PollsPollIdRoute = PollsPollIdRouteImport.update({
  id: '/polls/$pollId',
  path: '/polls/$pollId',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesConversationIdRoute = MessagesConversationIdRouteImport.update({
  id: '/messages/$conversationId',
  path: '/messages/$conversationId',
  getParentRoute: () => rootRouteImport,
} as any)
const GroceryListIdRoute = GroceryListIdRouteImport.update({
  id: '/grocery/$listId',
  path: '/grocery/$listId',
  getParentRoute: () => rootRouteImport,
} as any)
const DevLoginRoute = DevLoginRouteImport.update({
  id: '/dev/login',
  path: '/dev/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsSavedRoute = CollectionsSavedRouteImport.update({
  id: '/collections/saved',
  path: '/collections/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsBrowseRoute = CollectionsBrowseRouteImport.update({
  id: '/collections/browse',
  path: '/collections/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarsCalendarIdRoute = CalendarsCalendarIdRouteImport.update({
  id: '/calendars/$calendarId',
  path: '/calendars/$calendarId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadPdfRoute = ApiUploadPdfRouteImport.update({
  id: '/api/upload-pdf',
  path: '/api/upload-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRotateImageRoute = ApiRotateImageRouteImport.update({
  id: '/api/rotate-image',
  path: '/api/rotate-image',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameIndexRoute = UUsernameIndexRouteImport.update({
  id: '/u/$username/',
  path: '/u/$username/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesRecipeIdIndexRoute = RecipesRecipeIdIndexRouteImport.update({
  id: '/recipes/$recipeId/',
  path: '/recipes/$recipeId/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsCollectionIdIndexRoute =
  CollectionsCollectionIdIndexRouteImport.update({
    id: '/collections/$collectionId/',
    path: '/collections/$collectionId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthGoogleIndexRoute = AuthGoogleIndexRouteImport.update({
  id: '/auth/google/',
  path: '/auth/google/',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameFollowingRoute = UUsernameFollowingRouteImport.update({
  id: '/u/$username/following',
  path: '/u/$username/following',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameFollowersRoute = UUsernameFollowersRouteImport.update({
  id: '/u/$username/followers',
  path: '/u/$username/followers',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesRecipeIdPdfRoute = RecipesRecipeIdPdfRouteImport.update({
  id: '/recipes/$recipeId/pdf',
  path: '/recipes/$recipeId/pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesRecipeIdEditRoute = RecipesRecipeIdEditRouteImport.update({
  id: '/recipes/$recipeId/edit',
  path: '/recipes/$recipeId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesRecipeIdCookRoute = RecipesRecipeIdCookRouteImport.update({
  id: '/recipes/$recipeId/cook',
  path: '/recipes/$recipeId/cook',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsCollectionIdPdfRoute =
  CollectionsCollectionIdPdfRouteImport.update({
    id: '/collections/$collectionId/pdf',
    path: '/collections/$collectionId/pdf',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthGoogleCallbackRoute = AuthGoogleCallbackRouteImport.update({
  id: '/auth/google/callback',
  path: '/auth/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksStripeRoute = ApiWebhooksStripeRouteImport.update({
  id: '/api/webhooks/stripe',
  path: '/api/webhooks/stripe',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/pantry': typeof PantryRoute
  '/settings': typeof SettingsRoute
  '/subscribers-only': typeof SubscribersOnlyRoute
  '/api/rotate-image': typeof ApiRotateImageRoute
  '/api/upload': typeof ApiUploadRoute
  '/api/upload-pdf': typeof ApiUploadPdfRoute
  '/calendars/$calendarId': typeof CalendarsCalendarIdRoute
  '/collections/browse': typeof CollectionsBrowseRoute
  '/collections/saved': typeof CollectionsSavedRoute
  '/dev/login': typeof DevLoginRoute
  '/grocery/$listId': typeof GroceryListIdRoute
  '/messages/$conversationId': typeof MessagesConversationIdRoute
  '/polls/$pollId': typeof PollsPollIdRoute
  '/recipes/new': typeof RecipesNewRoute
  '/recipes/tags': typeof RecipesTagsRoute
  '/shared/$token': typeof SharedTokenRoute
  '/calendars/': typeof CalendarsIndexRoute
  '/collections/': typeof CollectionsIndexRoute
  '/grocery/': typeof GroceryIndexRoute
  '/messages/': typeof MessagesIndexRoute
  '/notifications/': typeof NotificationsIndexRoute
  '/polls/': typeof PollsIndexRoute
  '/recipes/': typeof RecipesIndexRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/collections/$collectionId/pdf': typeof CollectionsCollectionIdPdfRoute
  '/recipes/$recipeId/cook': typeof RecipesRecipeIdCookRoute
  '/recipes/$recipeId/edit': typeof RecipesRecipeIdEditRoute
  '/recipes/$recipeId/pdf': typeof RecipesRecipeIdPdfRoute
  '/u/$username/followers': typeof UUsernameFollowersRoute
  '/u/$username/following': typeof UUsernameFollowingRoute
  '/auth/google/': typeof AuthGoogleIndexRoute
  '/collections/$collectionId/': typeof CollectionsCollectionIdIndexRoute
  '/recipes/$recipeId/': typeof RecipesRecipeIdIndexRoute
  '/u/$username/': typeof UUsernameIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/pantry': typeof PantryRoute
  '/settings': typeof SettingsRoute
  '/subscribers-only': typeof SubscribersOnlyRoute
  '/api/rotate-image': typeof ApiRotateImageRoute
  '/api/upload': typeof ApiUploadRoute
  '/api/upload-pdf': typeof ApiUploadPdfRoute
  '/calendars/$calendarId': typeof CalendarsCalendarIdRoute
  '/collections/browse': typeof CollectionsBrowseRoute
  '/collections/saved': typeof CollectionsSavedRoute
  '/dev/login': typeof DevLoginRoute
  '/grocery/$listId': typeof GroceryListIdRoute
  '/messages/$conversationId': typeof MessagesConversationIdRoute
  '/polls/$pollId': typeof PollsPollIdRoute
  '/recipes/new': typeof RecipesNewRoute
  '/recipes/tags': typeof RecipesTagsRoute
  '/shared/$token': typeof SharedTokenRoute
  '/calendars': typeof CalendarsIndexRoute
  '/collections': typeof CollectionsIndexRoute
  '/grocery': typeof GroceryIndexRoute
  '/messages': typeof MessagesIndexRoute
  '/notifications': typeof NotificationsIndexRoute
  '/polls': typeof PollsIndexRoute
  '/recipes': typeof RecipesIndexRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/collections/$collectionId/pdf': typeof CollectionsCollectionIdPdfRoute
  '/recipes/$recipeId/cook': typeof RecipesRecipeIdCookRoute
  '/recipes/$recipeId/edit': typeof RecipesRecipeIdEditRoute
  '/recipes/$recipeId/pdf': typeof RecipesRecipeIdPdfRoute
  '/u/$username/followers': typeof UUsernameFollowersRoute
  '/u/$username/following': typeof UUsernameFollowingRoute
  '/auth/google': typeof AuthGoogleIndexRoute
  '/collections/$collectionId': typeof CollectionsCollectionIdIndexRoute
  '/recipes/$recipeId': typeof RecipesRecipeIdIndexRoute
  '/u/$username': typeof UUsernameIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/pantry': typeof PantryRoute
  '/settings': typeof SettingsRoute
  '/subscribers-only': typeof SubscribersOnlyRoute
  '/api/rotate-image': typeof ApiRotateImageRoute
  '/api/upload': typeof ApiUploadRoute
  '/api/upload-pdf': typeof ApiUploadPdfRoute
  '/calendars/$calendarId': typeof CalendarsCalendarIdRoute
  '/collections/browse': typeof CollectionsBrowseRoute
  '/collections/saved': typeof CollectionsSavedRoute
  '/dev/login': typeof DevLoginRoute
  '/grocery/$listId': typeof GroceryListIdRoute
  '/messages/$conversationId': typeof MessagesConversationIdRoute
  '/polls/$pollId': typeof PollsPollIdRoute
  '/recipes/new': typeof RecipesNewRoute
  '/recipes/tags': typeof RecipesTagsRoute
  '/shared/$token': typeof SharedTokenRoute
  '/calendars/': typeof CalendarsIndexRoute
  '/collections/': typeof CollectionsIndexRoute
  '/grocery/': typeof GroceryIndexRoute
  '/messages/': typeof MessagesIndexRoute
  '/notifications/': typeof NotificationsIndexRoute
  '/polls/': typeof PollsIndexRoute
  '/recipes/': typeof RecipesIndexRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/collections/$collectionId/pdf': typeof CollectionsCollectionIdPdfRoute
  '/recipes/$recipeId/cook': typeof RecipesRecipeIdCookRoute
  '/recipes/$recipeId/edit': typeof RecipesRecipeIdEditRoute
  '/recipes/$recipeId/pdf': typeof RecipesRecipeIdPdfRoute
  '/u/$username/followers': typeof UUsernameFollowersRoute
  '/u/$username/following': typeof UUsernameFollowingRoute
  '/auth/google/': typeof AuthGoogleIndexRoute
  '/collections/$collectionId/': typeof CollectionsCollectionIdIndexRoute
  '/recipes/$recipeId/': typeof RecipesRecipeIdIndexRoute
  '/u/$username/': typeof UUsernameIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/login'
    | '/pantry'
    | '/settings'
    | '/subscribers-only'
    | '/api/rotate-image'
    | '/api/upload'
    | '/api/upload-pdf'
    | '/calendars/$calendarId'
    | '/collections/browse'
    | '/collections/saved'
    | '/dev/login'
    | '/grocery/$listId'
    | '/messages/$conversationId'
    | '/polls/$pollId'
    | '/recipes/new'
    | '/recipes/tags'
    | '/shared/$token'
    | '/calendars/'
    | '/collections/'
    | '/grocery/'
    | '/messages/'
    | '/notifications/'
    | '/polls/'
    | '/recipes/'
    | '/api/webhooks/stripe'
    | '/auth/google/callback'
    | '/collections/$collectionId/pdf'
    | '/recipes/$recipeId/cook'
    | '/recipes/$recipeId/edit'
    | '/recipes/$recipeId/pdf'
    | '/u/$username/followers'
    | '/u/$username/following'
    | '/auth/google/'
    | '/collections/$collectionId/'
    | '/recipes/$recipeId/'
    | '/u/$username/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/login'
    | '/pantry'
    | '/settings'
    | '/subscribers-only'
    | '/api/rotate-image'
    | '/api/upload'
    | '/api/upload-pdf'
    | '/calendars/$calendarId'
    | '/collections/browse'
    | '/collections/saved'
    | '/dev/login'
    | '/grocery/$listId'
    | '/messages/$conversationId'
    | '/polls/$pollId'
    | '/recipes/new'
    | '/recipes/tags'
    | '/shared/$token'
    | '/calendars'
    | '/collections'
    | '/grocery'
    | '/messages'
    | '/notifications'
    | '/polls'
    | '/recipes'
    | '/api/webhooks/stripe'
    | '/auth/google/callback'
    | '/collections/$collectionId/pdf'
    | '/recipes/$recipeId/cook'
    | '/recipes/$recipeId/edit'
    | '/recipes/$recipeId/pdf'
    | '/u/$username/followers'
    | '/u/$username/following'
    | '/auth/google'
    | '/collections/$collectionId'
    | '/recipes/$recipeId'
    | '/u/$username'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/login'
    | '/pantry'
    | '/settings'
    | '/subscribers-only'
    | '/api/rotate-image'
    | '/api/upload'
    | '/api/upload-pdf'
    | '/calendars/$calendarId'
    | '/collections/browse'
    | '/collections/saved'
    | '/dev/login'
    | '/grocery/$listId'
    | '/messages/$conversationId'
    | '/polls/$pollId'
    | '/recipes/new'
    | '/recipes/tags'
    | '/shared/$token'
    | '/calendars/'
    | '/collections/'
    | '/grocery/'
    | '/messages/'
    | '/notifications/'
    | '/polls/'
    | '/recipes/'
    | '/api/webhooks/stripe'
    | '/auth/google/callback'
    | '/collections/$collectionId/pdf'
    | '/recipes/$recipeId/cook'
    | '/recipes/$recipeId/edit'
    | '/recipes/$recipeId/pdf'
    | '/u/$username/followers'
    | '/u/$username/following'
    | '/auth/google/'
    | '/collections/$collectionId/'
    | '/recipes/$recipeId/'
    | '/u/$username/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  LoginRoute: typeof LoginRoute
  PantryRoute: typeof PantryRoute
  SettingsRoute: typeof SettingsRoute
  SubscribersOnlyRoute: typeof SubscribersOnlyRoute
  ApiRotateImageRoute: typeof ApiRotateImageRoute
  ApiUploadRoute: typeof ApiUploadRoute
  ApiUploadPdfRoute: typeof ApiUploadPdfRoute
  CalendarsCalendarIdRoute: typeof CalendarsCalendarIdRoute
  CollectionsBrowseRoute: typeof CollectionsBrowseRoute
  CollectionsSavedRoute: typeof CollectionsSavedRoute
  DevLoginRoute: typeof DevLoginRoute
  GroceryListIdRoute: typeof GroceryListIdRoute
  MessagesConversationIdRoute: typeof MessagesConversationIdRoute
  PollsPollIdRoute: typeof PollsPollIdRoute
  RecipesNewRoute: typeof RecipesNewRoute
  RecipesTagsRoute: typeof RecipesTagsRoute
  SharedTokenRoute: typeof SharedTokenRoute
  CalendarsIndexRoute: typeof CalendarsIndexRoute
  CollectionsIndexRoute: typeof CollectionsIndexRoute
  GroceryIndexRoute: typeof GroceryIndexRoute
  MessagesIndexRoute: typeof MessagesIndexRoute
  NotificationsIndexRoute: typeof NotificationsIndexRoute
  PollsIndexRoute: typeof PollsIndexRoute
  RecipesIndexRoute: typeof RecipesIndexRoute
  ApiWebhooksStripeRoute: typeof ApiWebhooksStripeRoute
  AuthGoogleCallbackRoute: typeof AuthGoogleCallbackRoute
  CollectionsCollectionIdPdfRoute: typeof CollectionsCollectionIdPdfRoute
  RecipesRecipeIdCookRoute: typeof RecipesRecipeIdCookRoute
  RecipesRecipeIdEditRoute: typeof RecipesRecipeIdEditRoute
  RecipesRecipeIdPdfRoute: typeof RecipesRecipeIdPdfRoute
  UUsernameFollowersRoute: typeof UUsernameFollowersRoute
  UUsernameFollowingRoute: typeof UUsernameFollowingRoute
  AuthGoogleIndexRoute: typeof AuthGoogleIndexRoute
  CollectionsCollectionIdIndexRoute: typeof CollectionsCollectionIdIndexRoute
  RecipesRecipeIdIndexRoute: typeof RecipesRecipeIdIndexRoute
  UUsernameIndexRoute: typeof UUsernameIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/subscribers-only': {
      id: '/subscribers-only'
      path: '/subscribers-only'
      fullPath: '/subscribers-only'
      preLoaderRoute: typeof SubscribersOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pantry': {
      id: '/pantry'
      path: '/pantry'
      fullPath: '/pantry'
      preLoaderRoute: typeof PantryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/': {
      id: '/recipes/'
      path: '/recipes'
      fullPath: '/recipes/'
      preLoaderRoute: typeof RecipesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/polls/': {
      id: '/polls/'
      path: '/polls'
      fullPath: '/polls/'
      preLoaderRoute: typeof PollsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications/': {
      id: '/notifications/'
      path: '/notifications'
      fullPath: '/notifications/'
      preLoaderRoute: typeof NotificationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/': {
      id: '/messages/'
      path: '/messages'
      fullPath: '/messages/'
      preLoaderRoute: typeof MessagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grocery/': {
      id: '/grocery/'
      path: '/grocery'
      fullPath: '/grocery/'
      preLoaderRoute: typeof GroceryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/': {
      id: '/collections/'
      path: '/collections'
      fullPath: '/collections/'
      preLoaderRoute: typeof CollectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendars/': {
      id: '/calendars/'
      path: '/calendars'
      fullPath: '/calendars/'
      preLoaderRoute: typeof CalendarsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shared/$token': {
      id: '/shared/$token'
      path: '/shared/$token'
      fullPath: '/shared/$token'
      preLoaderRoute: typeof SharedTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/tags': {
      id: '/recipes/tags'
      path: '/recipes/tags'
      fullPath: '/recipes/tags'
      preLoaderRoute: typeof RecipesTagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/new': {
      id: '/recipes/new'
      path: '/recipes/new'
      fullPath: '/recipes/new'
      preLoaderRoute: typeof RecipesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/polls/$pollId': {
      id: '/polls/$pollId'
      path: '/polls/$pollId'
      fullPath: '/polls/$pollId'
      preLoaderRoute: typeof PollsPollIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/$conversationId': {
      id: '/messages/$conversationId'
      path: '/messages/$conversationId'
      fullPath: '/messages/$conversationId'
      preLoaderRoute: typeof MessagesConversationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grocery/$listId': {
      id: '/grocery/$listId'
      path: '/grocery/$listId'
      fullPath: '/grocery/$listId'
      preLoaderRoute: typeof GroceryListIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/login': {
      id: '/dev/login'
      path: '/dev/login'
      fullPath: '/dev/login'
      preLoaderRoute: typeof DevLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/saved': {
      id: '/collections/saved'
      path: '/collections/saved'
      fullPath: '/collections/saved'
      preLoaderRoute: typeof CollectionsSavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/browse': {
      id: '/collections/browse'
      path: '/collections/browse'
      fullPath: '/collections/browse'
      preLoaderRoute: typeof CollectionsBrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendars/$calendarId': {
      id: '/calendars/$calendarId'
      path: '/calendars/$calendarId'
      fullPath: '/calendars/$calendarId'
      preLoaderRoute: typeof CalendarsCalendarIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload-pdf': {
      id: '/api/upload-pdf'
      path: '/api/upload-pdf'
      fullPath: '/api/upload-pdf'
      preLoaderRoute: typeof ApiUploadPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rotate-image': {
      id: '/api/rotate-image'
      path: '/api/rotate-image'
      fullPath: '/api/rotate-image'
      preLoaderRoute: typeof ApiRotateImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username/': {
      id: '/u/$username/'
      path: '/u/$username'
      fullPath: '/u/$username/'
      preLoaderRoute: typeof UUsernameIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/$recipeId/': {
      id: '/recipes/$recipeId/'
      path: '/recipes/$recipeId'
      fullPath: '/recipes/$recipeId/'
      preLoaderRoute: typeof RecipesRecipeIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$collectionId/': {
      id: '/collections/$collectionId/'
      path: '/collections/$collectionId'
      fullPath: '/collections/$collectionId/'
      preLoaderRoute: typeof CollectionsCollectionIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/google/': {
      id: '/auth/google/'
      path: '/auth/google'
      fullPath: '/auth/google/'
      preLoaderRoute: typeof AuthGoogleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username/following': {
      id: '/u/$username/following'
      path: '/u/$username/following'
      fullPath: '/u/$username/following'
      preLoaderRoute: typeof UUsernameFollowingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username/followers': {
      id: '/u/$username/followers'
      path: '/u/$username/followers'
      fullPath: '/u/$username/followers'
      preLoaderRoute: typeof UUsernameFollowersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/$recipeId/pdf': {
      id: '/recipes/$recipeId/pdf'
      path: '/recipes/$recipeId/pdf'
      fullPath: '/recipes/$recipeId/pdf'
      preLoaderRoute: typeof RecipesRecipeIdPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/$recipeId/edit': {
      id: '/recipes/$recipeId/edit'
      path: '/recipes/$recipeId/edit'
      fullPath: '/recipes/$recipeId/edit'
      preLoaderRoute: typeof RecipesRecipeIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/$recipeId/cook': {
      id: '/recipes/$recipeId/cook'
      path: '/recipes/$recipeId/cook'
      fullPath: '/recipes/$recipeId/cook'
      preLoaderRoute: typeof RecipesRecipeIdCookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$collectionId/pdf': {
      id: '/collections/$collectionId/pdf'
      path: '/collections/$collectionId/pdf'
      fullPath: '/collections/$collectionId/pdf'
      preLoaderRoute: typeof CollectionsCollectionIdPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/google/callback': {
      id: '/auth/google/callback'
      path: '/auth/google/callback'
      fullPath: '/auth/google/callback'
      preLoaderRoute: typeof AuthGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/stripe': {
      id: '/api/webhooks/stripe'
      path: '/api/webhooks/stripe'
      fullPath: '/api/webhooks/stripe'
      preLoaderRoute: typeof ApiWebhooksStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  LoginRoute: LoginRoute,
  PantryRoute: PantryRoute,
  SettingsRoute: SettingsRoute,
  SubscribersOnlyRoute: SubscribersOnlyRoute,
  ApiRotateImageRoute: ApiRotateImageRoute,
  ApiUploadRoute: ApiUploadRoute,
  ApiUploadPdfRoute: ApiUploadPdfRoute,
  CalendarsCalendarIdRoute: CalendarsCalendarIdRoute,
  CollectionsBrowseRoute: CollectionsBrowseRoute,
  CollectionsSavedRoute: CollectionsSavedRoute,
  DevLoginRoute: DevLoginRoute,
  GroceryListIdRoute: GroceryListIdRoute,
  MessagesConversationIdRoute: MessagesConversationIdRoute,
  PollsPollIdRoute: PollsPollIdRoute,
  RecipesNewRoute: RecipesNewRoute,
  RecipesTagsRoute: RecipesTagsRoute,
  SharedTokenRoute: SharedTokenRoute,
  CalendarsIndexRoute: CalendarsIndexRoute,
  CollectionsIndexRoute: CollectionsIndexRoute,
  GroceryIndexRoute: GroceryIndexRoute,
  MessagesIndexRoute: MessagesIndexRoute,
  NotificationsIndexRoute: NotificationsIndexRoute,
  PollsIndexRoute: PollsIndexRoute,
  RecipesIndexRoute: RecipesIndexRoute,
  ApiWebhooksStripeRoute: ApiWebhooksStripeRoute,
  AuthGoogleCallbackRoute: AuthGoogleCallbackRoute,
  CollectionsCollectionIdPdfRoute: CollectionsCollectionIdPdfRoute,
  RecipesRecipeIdCookRoute: RecipesRecipeIdCookRoute,
  RecipesRecipeIdEditRoute: RecipesRecipeIdEditRoute,
  RecipesRecipeIdPdfRoute: RecipesRecipeIdPdfRoute,
  UUsernameFollowersRoute: UUsernameFollowersRoute,
  UUsernameFollowingRoute: UUsernameFollowingRoute,
  AuthGoogleIndexRoute: AuthGoogleIndexRoute,
  CollectionsCollectionIdIndexRoute: CollectionsCollectionIdIndexRoute,
  RecipesRecipeIdIndexRoute: RecipesRecipeIdIndexRoute,
  UUsernameIndexRoute: UUsernameIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
