/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecipesIndexRouteImport } from './routes/recipes/index'
import { Route as NotificationsIndexRouteImport } from './routes/notifications/index'
import { Route as GroceryIndexRouteImport } from './routes/grocery/index'
import { Route as CollectionsIndexRouteImport } from './routes/collections/index'
import { Route as CalendarsIndexRouteImport } from './routes/calendars/index'
import { Route as UUsernameRouteImport } from './routes/u/$username'
import { Route as SharedTokenRouteImport } from './routes/shared/$token'
import { Route as RecipesNewRouteImport } from './routes/recipes/new'
import { Route as GroceryListIdRouteImport } from './routes/grocery/$listId'
import { Route as CalendarsCalendarIdRouteImport } from './routes/calendars/$calendarId'
import { Route as ApiUploadPdfRouteImport } from './routes/api/upload-pdf'
import { Route as ApiUploadRouteImport } from './routes/api/upload'
import { Route as ApiRotateImageRouteImport } from './routes/api/rotate-image'
import { Route as RecipesRecipeIdIndexRouteImport } from './routes/recipes/$recipeId/index'
import { Route as CollectionsCollectionIdIndexRouteImport } from './routes/collections/$collectionId/index'
import { Route as AuthGoogleIndexRouteImport } from './routes/auth/google/index'
import { Route as RecipesRecipeIdPdfRouteImport } from './routes/recipes/$recipeId/pdf'
import { Route as RecipesRecipeIdEditRouteImport } from './routes/recipes/$recipeId/edit'
import { Route as CollectionsCollectionIdPdfRouteImport } from './routes/collections/$collectionId/pdf'
import { Route as AuthGoogleCallbackRouteImport } from './routes/auth/google/callback'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesIndexRoute = RecipesIndexRouteImport.update({
  id: '/recipes/',
  path: '/recipes/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsIndexRoute = NotificationsIndexRouteImport.update({
  id: '/notifications/',
  path: '/notifications/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroceryIndexRoute = GroceryIndexRouteImport.update({
  id: '/grocery/',
  path: '/grocery/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsIndexRoute = CollectionsIndexRouteImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarsIndexRoute = CalendarsIndexRouteImport.update({
  id: '/calendars/',
  path: '/calendars/',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const SharedTokenRoute = SharedTokenRouteImport.update({
  id: '/shared/$token',
  path: '/shared/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesNewRoute = RecipesNewRouteImport.update({
  id: '/recipes/new',
  path: '/recipes/new',
  getParentRoute: () => rootRouteImport,
} as any)
const GroceryListIdRoute = GroceryListIdRouteImport.update({
  id: '/grocery/$listId',
  path: '/grocery/$listId',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarsCalendarIdRoute = CalendarsCalendarIdRouteImport.update({
  id: '/calendars/$calendarId',
  path: '/calendars/$calendarId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadPdfRoute = ApiUploadPdfRouteImport.update({
  id: '/api/upload-pdf',
  path: '/api/upload-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRotateImageRoute = ApiRotateImageRouteImport.update({
  id: '/api/rotate-image',
  path: '/api/rotate-image',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesRecipeIdIndexRoute = RecipesRecipeIdIndexRouteImport.update({
  id: '/recipes/$recipeId/',
  path: '/recipes/$recipeId/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsCollectionIdIndexRoute =
  CollectionsCollectionIdIndexRouteImport.update({
    id: '/collections/$collectionId/',
    path: '/collections/$collectionId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthGoogleIndexRoute = AuthGoogleIndexRouteImport.update({
  id: '/auth/google/',
  path: '/auth/google/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesRecipeIdPdfRoute = RecipesRecipeIdPdfRouteImport.update({
  id: '/recipes/$recipeId/pdf',
  path: '/recipes/$recipeId/pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesRecipeIdEditRoute = RecipesRecipeIdEditRouteImport.update({
  id: '/recipes/$recipeId/edit',
  path: '/recipes/$recipeId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsCollectionIdPdfRoute =
  CollectionsCollectionIdPdfRouteImport.update({
    id: '/collections/$collectionId/pdf',
    path: '/collections/$collectionId/pdf',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthGoogleCallbackRoute = AuthGoogleCallbackRouteImport.update({
  id: '/auth/google/callback',
  path: '/auth/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/api/rotate-image': typeof ApiRotateImageRoute
  '/api/upload': typeof ApiUploadRoute
  '/api/upload-pdf': typeof ApiUploadPdfRoute
  '/calendars/$calendarId': typeof CalendarsCalendarIdRoute
  '/grocery/$listId': typeof GroceryListIdRoute
  '/recipes/new': typeof RecipesNewRoute
  '/shared/$token': typeof SharedTokenRoute
  '/u/$username': typeof UUsernameRoute
  '/calendars/': typeof CalendarsIndexRoute
  '/collections/': typeof CollectionsIndexRoute
  '/grocery/': typeof GroceryIndexRoute
  '/notifications/': typeof NotificationsIndexRoute
  '/recipes/': typeof RecipesIndexRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/collections/$collectionId/pdf': typeof CollectionsCollectionIdPdfRoute
  '/recipes/$recipeId/edit': typeof RecipesRecipeIdEditRoute
  '/recipes/$recipeId/pdf': typeof RecipesRecipeIdPdfRoute
  '/auth/google/': typeof AuthGoogleIndexRoute
  '/collections/$collectionId/': typeof CollectionsCollectionIdIndexRoute
  '/recipes/$recipeId/': typeof RecipesRecipeIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/api/rotate-image': typeof ApiRotateImageRoute
  '/api/upload': typeof ApiUploadRoute
  '/api/upload-pdf': typeof ApiUploadPdfRoute
  '/calendars/$calendarId': typeof CalendarsCalendarIdRoute
  '/grocery/$listId': typeof GroceryListIdRoute
  '/recipes/new': typeof RecipesNewRoute
  '/shared/$token': typeof SharedTokenRoute
  '/u/$username': typeof UUsernameRoute
  '/calendars': typeof CalendarsIndexRoute
  '/collections': typeof CollectionsIndexRoute
  '/grocery': typeof GroceryIndexRoute
  '/notifications': typeof NotificationsIndexRoute
  '/recipes': typeof RecipesIndexRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/collections/$collectionId/pdf': typeof CollectionsCollectionIdPdfRoute
  '/recipes/$recipeId/edit': typeof RecipesRecipeIdEditRoute
  '/recipes/$recipeId/pdf': typeof RecipesRecipeIdPdfRoute
  '/auth/google': typeof AuthGoogleIndexRoute
  '/collections/$collectionId': typeof CollectionsCollectionIdIndexRoute
  '/recipes/$recipeId': typeof RecipesRecipeIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/api/rotate-image': typeof ApiRotateImageRoute
  '/api/upload': typeof ApiUploadRoute
  '/api/upload-pdf': typeof ApiUploadPdfRoute
  '/calendars/$calendarId': typeof CalendarsCalendarIdRoute
  '/grocery/$listId': typeof GroceryListIdRoute
  '/recipes/new': typeof RecipesNewRoute
  '/shared/$token': typeof SharedTokenRoute
  '/u/$username': typeof UUsernameRoute
  '/calendars/': typeof CalendarsIndexRoute
  '/collections/': typeof CollectionsIndexRoute
  '/grocery/': typeof GroceryIndexRoute
  '/notifications/': typeof NotificationsIndexRoute
  '/recipes/': typeof RecipesIndexRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/collections/$collectionId/pdf': typeof CollectionsCollectionIdPdfRoute
  '/recipes/$recipeId/edit': typeof RecipesRecipeIdEditRoute
  '/recipes/$recipeId/pdf': typeof RecipesRecipeIdPdfRoute
  '/auth/google/': typeof AuthGoogleIndexRoute
  '/collections/$collectionId/': typeof CollectionsCollectionIdIndexRoute
  '/recipes/$recipeId/': typeof RecipesRecipeIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/settings'
    | '/api/rotate-image'
    | '/api/upload'
    | '/api/upload-pdf'
    | '/calendars/$calendarId'
    | '/grocery/$listId'
    | '/recipes/new'
    | '/shared/$token'
    | '/u/$username'
    | '/calendars/'
    | '/collections/'
    | '/grocery/'
    | '/notifications/'
    | '/recipes/'
    | '/auth/google/callback'
    | '/collections/$collectionId/pdf'
    | '/recipes/$recipeId/edit'
    | '/recipes/$recipeId/pdf'
    | '/auth/google/'
    | '/collections/$collectionId/'
    | '/recipes/$recipeId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/settings'
    | '/api/rotate-image'
    | '/api/upload'
    | '/api/upload-pdf'
    | '/calendars/$calendarId'
    | '/grocery/$listId'
    | '/recipes/new'
    | '/shared/$token'
    | '/u/$username'
    | '/calendars'
    | '/collections'
    | '/grocery'
    | '/notifications'
    | '/recipes'
    | '/auth/google/callback'
    | '/collections/$collectionId/pdf'
    | '/recipes/$recipeId/edit'
    | '/recipes/$recipeId/pdf'
    | '/auth/google'
    | '/collections/$collectionId'
    | '/recipes/$recipeId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/settings'
    | '/api/rotate-image'
    | '/api/upload'
    | '/api/upload-pdf'
    | '/calendars/$calendarId'
    | '/grocery/$listId'
    | '/recipes/new'
    | '/shared/$token'
    | '/u/$username'
    | '/calendars/'
    | '/collections/'
    | '/grocery/'
    | '/notifications/'
    | '/recipes/'
    | '/auth/google/callback'
    | '/collections/$collectionId/pdf'
    | '/recipes/$recipeId/edit'
    | '/recipes/$recipeId/pdf'
    | '/auth/google/'
    | '/collections/$collectionId/'
    | '/recipes/$recipeId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  ApiRotateImageRoute: typeof ApiRotateImageRoute
  ApiUploadRoute: typeof ApiUploadRoute
  ApiUploadPdfRoute: typeof ApiUploadPdfRoute
  CalendarsCalendarIdRoute: typeof CalendarsCalendarIdRoute
  GroceryListIdRoute: typeof GroceryListIdRoute
  RecipesNewRoute: typeof RecipesNewRoute
  SharedTokenRoute: typeof SharedTokenRoute
  UUsernameRoute: typeof UUsernameRoute
  CalendarsIndexRoute: typeof CalendarsIndexRoute
  CollectionsIndexRoute: typeof CollectionsIndexRoute
  GroceryIndexRoute: typeof GroceryIndexRoute
  NotificationsIndexRoute: typeof NotificationsIndexRoute
  RecipesIndexRoute: typeof RecipesIndexRoute
  AuthGoogleCallbackRoute: typeof AuthGoogleCallbackRoute
  CollectionsCollectionIdPdfRoute: typeof CollectionsCollectionIdPdfRoute
  RecipesRecipeIdEditRoute: typeof RecipesRecipeIdEditRoute
  RecipesRecipeIdPdfRoute: typeof RecipesRecipeIdPdfRoute
  AuthGoogleIndexRoute: typeof AuthGoogleIndexRoute
  CollectionsCollectionIdIndexRoute: typeof CollectionsCollectionIdIndexRoute
  RecipesRecipeIdIndexRoute: typeof RecipesRecipeIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/': {
      id: '/recipes/'
      path: '/recipes'
      fullPath: '/recipes/'
      preLoaderRoute: typeof RecipesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications/': {
      id: '/notifications/'
      path: '/notifications'
      fullPath: '/notifications/'
      preLoaderRoute: typeof NotificationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grocery/': {
      id: '/grocery/'
      path: '/grocery'
      fullPath: '/grocery/'
      preLoaderRoute: typeof GroceryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/': {
      id: '/collections/'
      path: '/collections'
      fullPath: '/collections/'
      preLoaderRoute: typeof CollectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendars/': {
      id: '/calendars/'
      path: '/calendars'
      fullPath: '/calendars/'
      preLoaderRoute: typeof CalendarsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shared/$token': {
      id: '/shared/$token'
      path: '/shared/$token'
      fullPath: '/shared/$token'
      preLoaderRoute: typeof SharedTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/new': {
      id: '/recipes/new'
      path: '/recipes/new'
      fullPath: '/recipes/new'
      preLoaderRoute: typeof RecipesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grocery/$listId': {
      id: '/grocery/$listId'
      path: '/grocery/$listId'
      fullPath: '/grocery/$listId'
      preLoaderRoute: typeof GroceryListIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendars/$calendarId': {
      id: '/calendars/$calendarId'
      path: '/calendars/$calendarId'
      fullPath: '/calendars/$calendarId'
      preLoaderRoute: typeof CalendarsCalendarIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload-pdf': {
      id: '/api/upload-pdf'
      path: '/api/upload-pdf'
      fullPath: '/api/upload-pdf'
      preLoaderRoute: typeof ApiUploadPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rotate-image': {
      id: '/api/rotate-image'
      path: '/api/rotate-image'
      fullPath: '/api/rotate-image'
      preLoaderRoute: typeof ApiRotateImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/$recipeId/': {
      id: '/recipes/$recipeId/'
      path: '/recipes/$recipeId'
      fullPath: '/recipes/$recipeId/'
      preLoaderRoute: typeof RecipesRecipeIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$collectionId/': {
      id: '/collections/$collectionId/'
      path: '/collections/$collectionId'
      fullPath: '/collections/$collectionId/'
      preLoaderRoute: typeof CollectionsCollectionIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/google/': {
      id: '/auth/google/'
      path: '/auth/google'
      fullPath: '/auth/google/'
      preLoaderRoute: typeof AuthGoogleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/$recipeId/pdf': {
      id: '/recipes/$recipeId/pdf'
      path: '/recipes/$recipeId/pdf'
      fullPath: '/recipes/$recipeId/pdf'
      preLoaderRoute: typeof RecipesRecipeIdPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/$recipeId/edit': {
      id: '/recipes/$recipeId/edit'
      path: '/recipes/$recipeId/edit'
      fullPath: '/recipes/$recipeId/edit'
      preLoaderRoute: typeof RecipesRecipeIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$collectionId/pdf': {
      id: '/collections/$collectionId/pdf'
      path: '/collections/$collectionId/pdf'
      fullPath: '/collections/$collectionId/pdf'
      preLoaderRoute: typeof CollectionsCollectionIdPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/google/callback': {
      id: '/auth/google/callback'
      path: '/auth/google/callback'
      fullPath: '/auth/google/callback'
      preLoaderRoute: typeof AuthGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  ApiRotateImageRoute: ApiRotateImageRoute,
  ApiUploadRoute: ApiUploadRoute,
  ApiUploadPdfRoute: ApiUploadPdfRoute,
  CalendarsCalendarIdRoute: CalendarsCalendarIdRoute,
  GroceryListIdRoute: GroceryListIdRoute,
  RecipesNewRoute: RecipesNewRoute,
  SharedTokenRoute: SharedTokenRoute,
  UUsernameRoute: UUsernameRoute,
  CalendarsIndexRoute: CalendarsIndexRoute,
  CollectionsIndexRoute: CollectionsIndexRoute,
  GroceryIndexRoute: GroceryIndexRoute,
  NotificationsIndexRoute: NotificationsIndexRoute,
  RecipesIndexRoute: RecipesIndexRoute,
  AuthGoogleCallbackRoute: AuthGoogleCallbackRoute,
  CollectionsCollectionIdPdfRoute: CollectionsCollectionIdPdfRoute,
  RecipesRecipeIdEditRoute: RecipesRecipeIdEditRoute,
  RecipesRecipeIdPdfRoute: RecipesRecipeIdPdfRoute,
  AuthGoogleIndexRoute: AuthGoogleIndexRoute,
  CollectionsCollectionIdIndexRoute: CollectionsCollectionIdIndexRoute,
  RecipesRecipeIdIndexRoute: RecipesRecipeIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
