/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecipesIndexRouteImport } from './routes/recipes/index'
import { Route as CollectionsIndexRouteImport } from './routes/collections/index'
import { Route as UUsernameRouteImport } from './routes/u/$username'
import { Route as SharedTokenRouteImport } from './routes/shared/$token'
import { Route as RecipesNewRouteImport } from './routes/recipes/new'
import { Route as CollectionsCollectionIdRouteImport } from './routes/collections/$collectionId'
import { Route as ApiUploadRouteImport } from './routes/api/upload'
import { Route as RecipesRecipeIdIndexRouteImport } from './routes/recipes/$recipeId/index'
import { Route as AuthGoogleIndexRouteImport } from './routes/auth/google/index'
import { Route as RecipesRecipeIdEditRouteImport } from './routes/recipes/$recipeId/edit'
import { Route as AuthGoogleCallbackRouteImport } from './routes/auth/google/callback'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesIndexRoute = RecipesIndexRouteImport.update({
  id: '/recipes/',
  path: '/recipes/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsIndexRoute = CollectionsIndexRouteImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const SharedTokenRoute = SharedTokenRouteImport.update({
  id: '/shared/$token',
  path: '/shared/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesNewRoute = RecipesNewRouteImport.update({
  id: '/recipes/new',
  path: '/recipes/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsCollectionIdRoute = CollectionsCollectionIdRouteImport.update({
  id: '/collections/$collectionId',
  path: '/collections/$collectionId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesRecipeIdIndexRoute = RecipesRecipeIdIndexRouteImport.update({
  id: '/recipes/$recipeId/',
  path: '/recipes/$recipeId/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGoogleIndexRoute = AuthGoogleIndexRouteImport.update({
  id: '/auth/google/',
  path: '/auth/google/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesRecipeIdEditRoute = RecipesRecipeIdEditRouteImport.update({
  id: '/recipes/$recipeId/edit',
  path: '/recipes/$recipeId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGoogleCallbackRoute = AuthGoogleCallbackRouteImport.update({
  id: '/auth/google/callback',
  path: '/auth/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/api/upload': typeof ApiUploadRoute
  '/collections/$collectionId': typeof CollectionsCollectionIdRoute
  '/recipes/new': typeof RecipesNewRoute
  '/shared/$token': typeof SharedTokenRoute
  '/u/$username': typeof UUsernameRoute
  '/collections/': typeof CollectionsIndexRoute
  '/recipes/': typeof RecipesIndexRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/recipes/$recipeId/edit': typeof RecipesRecipeIdEditRoute
  '/auth/google/': typeof AuthGoogleIndexRoute
  '/recipes/$recipeId/': typeof RecipesRecipeIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/api/upload': typeof ApiUploadRoute
  '/collections/$collectionId': typeof CollectionsCollectionIdRoute
  '/recipes/new': typeof RecipesNewRoute
  '/shared/$token': typeof SharedTokenRoute
  '/u/$username': typeof UUsernameRoute
  '/collections': typeof CollectionsIndexRoute
  '/recipes': typeof RecipesIndexRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/recipes/$recipeId/edit': typeof RecipesRecipeIdEditRoute
  '/auth/google': typeof AuthGoogleIndexRoute
  '/recipes/$recipeId': typeof RecipesRecipeIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/api/upload': typeof ApiUploadRoute
  '/collections/$collectionId': typeof CollectionsCollectionIdRoute
  '/recipes/new': typeof RecipesNewRoute
  '/shared/$token': typeof SharedTokenRoute
  '/u/$username': typeof UUsernameRoute
  '/collections/': typeof CollectionsIndexRoute
  '/recipes/': typeof RecipesIndexRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/recipes/$recipeId/edit': typeof RecipesRecipeIdEditRoute
  '/auth/google/': typeof AuthGoogleIndexRoute
  '/recipes/$recipeId/': typeof RecipesRecipeIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/settings'
    | '/api/upload'
    | '/collections/$collectionId'
    | '/recipes/new'
    | '/shared/$token'
    | '/u/$username'
    | '/collections/'
    | '/recipes/'
    | '/auth/google/callback'
    | '/recipes/$recipeId/edit'
    | '/auth/google/'
    | '/recipes/$recipeId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/settings'
    | '/api/upload'
    | '/collections/$collectionId'
    | '/recipes/new'
    | '/shared/$token'
    | '/u/$username'
    | '/collections'
    | '/recipes'
    | '/auth/google/callback'
    | '/recipes/$recipeId/edit'
    | '/auth/google'
    | '/recipes/$recipeId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/settings'
    | '/api/upload'
    | '/collections/$collectionId'
    | '/recipes/new'
    | '/shared/$token'
    | '/u/$username'
    | '/collections/'
    | '/recipes/'
    | '/auth/google/callback'
    | '/recipes/$recipeId/edit'
    | '/auth/google/'
    | '/recipes/$recipeId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  ApiUploadRoute: typeof ApiUploadRoute
  CollectionsCollectionIdRoute: typeof CollectionsCollectionIdRoute
  RecipesNewRoute: typeof RecipesNewRoute
  SharedTokenRoute: typeof SharedTokenRoute
  UUsernameRoute: typeof UUsernameRoute
  CollectionsIndexRoute: typeof CollectionsIndexRoute
  RecipesIndexRoute: typeof RecipesIndexRoute
  AuthGoogleCallbackRoute: typeof AuthGoogleCallbackRoute
  RecipesRecipeIdEditRoute: typeof RecipesRecipeIdEditRoute
  AuthGoogleIndexRoute: typeof AuthGoogleIndexRoute
  RecipesRecipeIdIndexRoute: typeof RecipesRecipeIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/': {
      id: '/recipes/'
      path: '/recipes'
      fullPath: '/recipes/'
      preLoaderRoute: typeof RecipesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/': {
      id: '/collections/'
      path: '/collections'
      fullPath: '/collections/'
      preLoaderRoute: typeof CollectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shared/$token': {
      id: '/shared/$token'
      path: '/shared/$token'
      fullPath: '/shared/$token'
      preLoaderRoute: typeof SharedTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/new': {
      id: '/recipes/new'
      path: '/recipes/new'
      fullPath: '/recipes/new'
      preLoaderRoute: typeof RecipesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$collectionId': {
      id: '/collections/$collectionId'
      path: '/collections/$collectionId'
      fullPath: '/collections/$collectionId'
      preLoaderRoute: typeof CollectionsCollectionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/$recipeId/': {
      id: '/recipes/$recipeId/'
      path: '/recipes/$recipeId'
      fullPath: '/recipes/$recipeId/'
      preLoaderRoute: typeof RecipesRecipeIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/google/': {
      id: '/auth/google/'
      path: '/auth/google'
      fullPath: '/auth/google/'
      preLoaderRoute: typeof AuthGoogleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/$recipeId/edit': {
      id: '/recipes/$recipeId/edit'
      path: '/recipes/$recipeId/edit'
      fullPath: '/recipes/$recipeId/edit'
      preLoaderRoute: typeof RecipesRecipeIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/google/callback': {
      id: '/auth/google/callback'
      path: '/auth/google/callback'
      fullPath: '/auth/google/callback'
      preLoaderRoute: typeof AuthGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  ApiUploadRoute: ApiUploadRoute,
  CollectionsCollectionIdRoute: CollectionsCollectionIdRoute,
  RecipesNewRoute: RecipesNewRoute,
  SharedTokenRoute: SharedTokenRoute,
  UUsernameRoute: UUsernameRoute,
  CollectionsIndexRoute: CollectionsIndexRoute,
  RecipesIndexRoute: RecipesIndexRoute,
  AuthGoogleCallbackRoute: AuthGoogleCallbackRoute,
  RecipesRecipeIdEditRoute: RecipesRecipeIdEditRoute,
  AuthGoogleIndexRoute: AuthGoogleIndexRoute,
  RecipesRecipeIdIndexRoute: RecipesRecipeIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
